Python 3.11.5 (tags/v3.11.5:cce6ba9, Aug 24 2023, 14:38:34) [MSC v.1936 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> n = int(input("Введите количество чисел: "))
... 
... numbers = []
... for i in range(n):
...     number = int(input("Введите число: "))
...     numbers.append(number)
... 
... print("Исходный список:", numbers)
... 
... 
... numbers = [numbers[i] for i in range(len(numbers)) if i % 2 == 0]
... 
... print("Список после удаления элементов по нечетным индексам:", numbers)
